# Generated by Django 5.0.4 on 2026-04-25 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del plan de entrenamiento.', max_length=100, verbose_name='nombre del plan')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general del plan y sus objetivos.', null=True, verbose_name='descripción')),
                ('area_muscular', models.CharField(choices=[('PECHO', 'Pecho'), ('ESPALDA', 'Espalda'), ('PIERNAS', 'Piernas'), ('HOMBROS', 'Hombros'), ('BRAZOS', 'Brazos (Bíceps/Tríceps)'), ('ABDOMEN', 'Abdomen/Core'), ('GLUTEOS', 'Glúteos'), ('CARDIO', 'Cardiovascular'), ('Cuerpo_COMPLETO', 'Cuerpo Completo'), ('OTRO', 'Otro')], help_text='Grupo muscular principal que trabaja el plan.', max_length=20, verbose_name='área muscular objetivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se creó el plan.', verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última modificación del plan.', verbose_name='fecha de última actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el plan está activo y disponible para asignar.', verbose_name='activo')),
                ('nivel_dificultad', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='INTERMEDIO', help_text='Nivel de dificultad del plan.', max_length=20, verbose_name='nivel de dificultad')),
                ('duracion_semanas', models.PositiveIntegerField(default=4, help_text='Duración estimada del plan en semanas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='duración (semanas)')),
                ('observaciones_generales', models.TextField(blank=True, help_text='Notas adicionales sobre el plan.', null=True, verbose_name='observaciones generales')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Personal/entrenador que creó el plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('usuarios_asignados', models.ManyToManyField(blank=True, help_text='Usuarios que tienen asignado este plan.', related_name='planes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='usuarios asignados')),
            ],
            options={
                'verbose_name': 'plan de entrenamiento',
                'verbose_name_plural': 'planes de entrenamiento',
                'ordering': ['-fecha_creacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPlanUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de asignación')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ASIGNADO', max_length=20, verbose_name='estado')),
                ('progreso_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progreso (%)')),
                ('observaciones_seguimiento', models.TextField(blank=True, null=True, verbose_name='observaciones de seguimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_planes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_usuarios', to='planes.planentrenamiento')),
            ],
            options={
                'verbose_name': 'historial de plan por usuario',
                'verbose_name_plural': 'historial de planes por usuario',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del ejercicio (ej: Press de banca, Sentadilla).', max_length=150, verbose_name='nombre del ejercicio')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la técnica del ejercicio.', null=True, verbose_name='descripción')),
                ('series', models.PositiveIntegerField(help_text='Cantidad de series a realizar.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='número de series')),
                ('repeticiones', models.CharField(help_text='Número de repeticiones (ej: "10-12", "15", "Fallo").', max_length=50, verbose_name='repeticiones')),
                ('descanso_segundos', models.PositiveIntegerField(default=60, help_text='Tiempo de descanso entre series en segundos.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='descanso (segundos)')),
                ('peso_sugerido', models.DecimalField(blank=True, decimal_places=2, help_text='Peso sugerido en kilogramos (opcional).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='peso sugerido (kg)')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden en que se realiza el ejercicio dentro del plan.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='orden de ejecución')),
                ('area_especifica', models.CharField(blank=True, help_text='Músculo o zona específica que trabaja el ejercicio.', max_length=100, null=True, verbose_name='área específica')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la ejecución del ejercicio.', null=True, verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el ejercicio está activo en el plan.', verbose_name='activo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='planes.planentrenamiento', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'ordering': ['plan', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='planentrenamiento',
            index=models.Index(fields=['area_muscular'], name='idx_plan_area'),
        ),
        migrations.AddIndex(
            model_name='planentrenamiento',
            index=models.Index(fields=['activo'], name='idx_plan_activo'),
        ),
        migrations.AddIndex(
            model_name='planentrenamiento',
            index=models.Index(fields=['nivel_dificultad'], name='idx_plan_nivel'),
        ),
        migrations.AddIndex(
            model_name='historialplanusuario',
            index=models.Index(fields=['usuario', 'estado'], name='idx_historial_usuario_estado'),
        ),
        migrations.AddIndex(
            model_name='historialplanusuario',
            index=models.Index(fields=['fecha_asignacion'], name='idx_historial_fecha'),
        ),
        migrations.AddIndex(
            model_name='ejercicio',
            index=models.Index(fields=['plan', 'orden'], name='idx_ejercicio_plan_orden'),
        ),
        migrations.AddIndex(
            model_name='ejercicio',
            index=models.Index(fields=['area_especifica'], name='idx_ejercicio_area'),
        ),
        migrations.AddConstraint(
            model_name='ejercicio',
            constraint=models.UniqueConstraint(fields=('plan', 'nombre', 'orden'), name='unique_ejercicio_plan_nombre_orden', violation_error_message='Ya existe un ejercicio con este nombre y orden en el plan.'),
        ),
    ]
