# Generated by Django 5.0.4 on 2026-04-25 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenAsistenciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='fecha')),
                ('total_ingresos', models.PositiveIntegerField(default=0, verbose_name='total ingresos')),
                ('total_sesiones_consumidas', models.PositiveIntegerField(default=0, verbose_name='total sesiones')),
                ('usuarios_unicos', models.PositiveIntegerField(default=0, verbose_name='usuarios únicos')),
                ('membresias_utilizadas', models.PositiveIntegerField(default=0, verbose_name='membresías usadas')),
            ],
            options={
                'verbose_name': 'resumen de asistencia diaria',
                'verbose_name_plural': 'resúmenes de asistencia diaria',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del registro de asistencia.', verbose_name='fecha y hora')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha del registro (para índices y filtros rápidos).', verbose_name='fecha')),
                ('metodo_ingreso', models.CharField(choices=[('MANUAL', 'Manual (Personal)'), ('AUTOMATICO', 'Automático (Sistema)'), ('QR', 'Código QR')], default='MANUAL', help_text='Cómo se registró el ingreso.', max_length=15, verbose_name='método de ingreso')),
                ('tipo_registro', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida')], default='INGRESO', help_text='Indica si es ingreso o salida.', max_length=10, verbose_name='tipo de registro')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el registro.', null=True, verbose_name='observaciones')),
                ('es_consumo_sesion', models.BooleanField(default=True, help_text='Indica si este registro consume una sesión de la membresía.', verbose_name='¿consume sesión?')),
                ('session_consumida', models.BooleanField(default=False, help_text='Confirma si ya se descontó la sesión de la membresía.', verbose_name='sesión consumida')),
                ('membresia', models.ForeignKey(help_text='Membresía activa al momento del registro.', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='membresias.membresia', verbose_name='membresía')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Personal que registró la asistencia (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de asistencia',
                'verbose_name_plural': 'registros de asistencia',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='idx_asist_usuario_fecha'), models.Index(fields=['membresia', 'fecha'], name='idx_asist_membresia_fecha'), models.Index(fields=['fecha'], name='idx_asist_fecha'), models.Index(fields=['tipo_registro'], name='idx_asist_tipo')],
            },
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha', 'tipo_registro'), name='unique_asistencia_usuario_fecha_tipo', violation_error_message='Ya existe un registro de este tipo para el usuario en esta fecha.'),
        ),
    ]
