# Generated by Django 5.0.4 on 2026-04-25 06:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Mensual (30 días)'), ('BIMESTRAL', 'Bimestral (60 días)'), ('TRIMESTRAL', 'Trimestral (90 días)'), ('SEMESTRAL', 'Semestral (180 días)')], help_text='Duración de la membresía.', max_length=20, verbose_name='tipo de membresía')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Valor pagado por la membresía en pesos colombianos.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que inicia la vigencia de la membresía.', verbose_name='fecha de inicio')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha en que expira la membresía.', verbose_name='fecha de vencimiento')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro de la membresía.', verbose_name='fecha de compra')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida')], default='ACTIVA', help_text='Estado actual de la membresía.', max_length=10, verbose_name='estado')),
                ('sesiones_totales', models.PositiveIntegerField(default=0, help_text='Número total de sesiones permitidas (0 = ilimitadas).', verbose_name='sesiones totales')),
                ('sesiones_consumidas', models.PositiveIntegerField(default=0, help_text='Número de sesiones ya utilizadas.', verbose_name='sesiones consumidas')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la membresía.', null=True, verbose_name='observaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
                'ordering': ['-fecha_inicio', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida')], max_length=10)),
                ('estado_nuevo', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida')], max_length=10)),
                ('motivo', models.CharField(blank=True, help_text='Motivo del cambio de estado (vencimiento, agotamiento de sesiones, etc.)', max_length=200, null=True)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='membresias.membresia')),
            ],
            options={
                'verbose_name': 'historial de membresía',
                'verbose_name_plural': 'historial de membresías',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='membresia',
            index=models.Index(fields=['usuario', 'estado'], name='idx_memb_usuario_estado'),
        ),
        migrations.AddIndex(
            model_name='membresia',
            index=models.Index(fields=['fecha_vencimiento'], name='idx_memb_vencimiento'),
        ),
        migrations.AddIndex(
            model_name='membresia',
            index=models.Index(fields=['estado'], name='idx_memb_estado'),
        ),
    ]
