# Generated by Django 5.0.4 on 2026-04-24 07:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono')),
                ('role', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('PERSONAL', 'Personal'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=15, verbose_name='rol en el sistema')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura en centímetros.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(50.0)], verbose_name='altura (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Se calcula automáticamente al guardar peso y altura.', max_digits=5, null=True, verbose_name='Índice de Masa Corporal')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='idx_usuario_email'), models.Index(fields=['role'], name='idx_usuario_role')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
